export const rankingFifa = {

    "Argentina": 1,
    "França": 2,
    "Espanha": 3,
    "Inglaterra": 4,
    "Portugal": 5,
    "Brasil": 6,
    "Marrocos": 7,
    "Holanda": 8,
    "Alemanha": 9,
    "Bélgica": 10,
    "Croácia": 11,
    "Italia": 12,
    "México": 13,
    "Colômbia": 14,
    "Estados Unidos": 15,
    "Senegal": 16,
    "Japão": 17,
    "Uruguai": 18,
};
